import { ScadBuilder } from "../../openscad/scad-builder";
import { createManifest, clampParameters, applyDefaults } from "../../openscad/manifest";
import type {
  ModelParameters,
  ParameterDef,
  GenerateScadResult,
} from "../../openscad/types";

/** @param shankDiameter default=6 min=2 max=30 description="Diameter of the bolt shank (mm)" */
/** @param shankLength default=20 min=5 max=100 description="Length of the bolt shank (mm)" */
/** @param headDiameter default=10 min=4 max=30 description="Across-flats diameter of the hex head (mm)" */
/** @param headHeight default=4 min=1 max=20 description="Height of the hex head (mm)" */
/** @param threadPitch default=1 min=0.5 max=4 description="Thread pitch (mm)" */
/** @param fn default=64 min=16 max=128 description="Resolution ($fn) for curved surfaces" */

export const parameterDefs: ParameterDef[] = [
  { name: "shankDiameter", default: 6, min: 2, max: 30, description: "Diameter of the bolt shank (mm)" },
  { name: "shankLength", default: 20, min: 5, max: 100, description: "Length of the bolt shank (mm)" },
  { name: "headDiameter", default: 10, min: 4, max: 30, description: "Across-flats diameter of the hex head (mm)" },
  { name: "headHeight", default: 4, min: 1, max: 20, description: "Height of the hex head (mm)" },
  { name: "threadPitch", default: 1, min: 0.5, max: 4, description: "Thread pitch (mm)" },
  { name: "fn", default: 64, min: 16, max: 128, description: "Resolution ($fn) for curved surfaces" },
];

export const defaultParams: ModelParameters = Object.fromEntries(
  parameterDefs.map((p) => [p.name, p.default])
);

export function generateScad(params: ModelParameters): GenerateScadResult {
  const resolved = clampParameters(applyDefaults(params, parameterDefs), parameterDefs);

  const shankDiameter = Number(resolved.shankDiameter);
  const shankLength = Number(resolved.shankLength);
  const headDiameter = Math.min(30, Number(resolved.headDiameter));
  const headHeight = Number(resolved.headHeight);
  const threadPitch = Number(resolved.threadPitch);
  const fn = Number(resolved.fn);

  // Hex head: circumscribed circle radius from across-flats diameter
  const hexRadius = headDiameter / (2 * Math.cos(Math.PI / 6));

  const s = new ScadBuilder("openscad-bolt/model.ts");

  s.comment(`Parametric Hex Bolt — generated by vibecad-studio`);
  s.comment(`shank: ⌀${shankDiameter} × ${shankLength}mm, head: ⌀${headDiameter} × ${headHeight}mm`);
  s.raw("");

  // Module: hex_head
  s.moduleDecl("hex_head", [`d=${headDiameter}`, `h=${headHeight}`], () => {
    s.raw(`  cylinder(h=h, r=${hexRadius.toFixed(4)}, $fn=6);`);
  });

  s.raw("");

  // Module: shank with simplified thread grooves
  s.moduleDecl("shank", [`d=${shankDiameter}`, `l=${shankLength}`, `pitch=${threadPitch}`], () => {
    s.difference(() => {
      s.raw(`    cylinder(h=l, r=d/2, $fn=${fn});`);
      // Thread groove (simplified as a helical cut impression)
      s.raw(`    for (i = [0 : pitch : l]) {`);
      s.raw(`      translate([0, 0, i])`);
      s.raw(`        rotate_extrude($fn=${fn})`);
      s.raw(`          translate([d/2 - pitch*0.4, 0, 0])`);
      s.raw(`            circle(r=pitch*0.35, $fn=16);`);
      s.raw(`    }`);
    });
  });

  s.raw("");

  // Compose the bolt
  s.comment("Assemble the bolt");
  s.union(() => {
    s.translate([0, 0, shankLength], () => {
      s.moduleCall("hex_head");
    });
    s.moduleCall("shank");
  });

  const manifest = createManifest("openscad-bolt", parameterDefs);

  return {
    scad: s.build(),
    manifest,
    sourceMap: { entries: s.getSourceMap() },
  };
}
